version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.10.0
  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0

    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
    AIRFLOW__WEBSERVER__SECRET_KEY : mysupersecretkey123

    

  user: "50000"

  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./datasets:/opt/airflow/datasets
    - ./requirements.txt:/opt/airflow/requirements.txt

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2-bookworm

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
        exec airflow webserver
      "
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
        exec airflow scheduler
      "
    depends_on:
      - airflow-init

  airflow-worker:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
        exec airflow celery worker
      "
    depends_on:
      - airflow-scheduler

  airflow-triggerer:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
        exec airflow triggerer
      "
    depends_on:
      - airflow-scheduler

  airflow-init:
    <<: *airflow-common
    entrypoint: bash
    command: >
      -c "
        pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
        airflow db upgrade &&
        airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com &&
        airflow db check
      "
    depends_on:
      - postgres
      - redis

volumes:
  postgres-db-volume:
